# ventas_comidaRapida
Proyectos desarrollados en Netbeans
package Frame;

import Conecta.Base;
import java.beans.Statement;
import java.sql.Connection;
import java.sql.ResultSet;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
/**
 *
 * @author Cristian
 */
public class Principal extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */
    
     private int opcion;

    Base acc=null;
     
    Principal Accion;
        
    
    Connection con;
    Statement stc=null;
    ResultSet rs=null;
    
   String completo, sandwich, pizza, tamaño, beber, mayo, ketchup, mostaza, americana, tomate, palta, chucrut
           ,EQueso, carne, choricillos, choclos, palmitos, esparragos;
           
    public Principal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        btgTipoPedido = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        rbtCompleto = new javax.swing.JRadioButton();
        rbtSandwich = new javax.swing.JRadioButton();
        rbtPizza = new javax.swing.JRadioButton();
        jPanel2 = new javax.swing.JPanel();
        jcbTamano = new javax.swing.JComboBox();
        jcbBeber = new javax.swing.JComboBox();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        panelCS = new javax.swing.JPanel();
        jcbMayo = new javax.swing.JCheckBox();
        jcbKetchup = new javax.swing.JCheckBox();
        jcbMostaza = new javax.swing.JCheckBox();
        jcbAmericana = new javax.swing.JCheckBox();
        jcbTomate = new javax.swing.JCheckBox();
        jcbPalta = new javax.swing.JCheckBox();
        jcbChucrut = new javax.swing.JCheckBox();
        panelP = new javax.swing.JPanel();
        jcbExtraQueso = new javax.swing.JCheckBox();
        jcbCarne = new javax.swing.JCheckBox();
        jcbChoricillos = new javax.swing.JCheckBox();
        jcbChoclo = new javax.swing.JCheckBox();
        jcbPalmitos = new javax.swing.JCheckBox();
        jcbEsparrago = new javax.swing.JCheckBox();
        jPanel6 = new javax.swing.JPanel();
        jbtCalcular = new javax.swing.JButton();
        jbtGuardar = new javax.swing.JButton();
        jbtSalir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Ventas - MandibulAtomica");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Tipo Pedido"));

        btgTipoPedido.add(rbtCompleto);
        rbtCompleto.setText("Completo");
        rbtCompleto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtCompletoActionPerformed(evt);
            }
        });

        btgTipoPedido.add(rbtSandwich);
        rbtSandwich.setText("Sandwich");
        rbtSandwich.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtSandwichActionPerformed(evt);
            }
        });

        btgTipoPedido.add(rbtPizza);
        rbtPizza.setText("Pizza");
        rbtPizza.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtPizzaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(rbtCompleto))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(rbtSandwich)
                            .addComponent(rbtPizza))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(rbtCompleto)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(rbtSandwich)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(rbtPizza)
                .addContainerGap(9, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Seleccione"));

        jcbTamano.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "<Selecione>", "Grande", "Mediano", "Chico", " " }));

        jcbBeber.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "<Seleccione>", "Bebida Lata", "Jugo Natural", "Café", "Té" }));

        jLabel1.setText("Tamaño");

        jLabel2.setText("Para Beber");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jcbTamano, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(48, 48, 48)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jcbBeber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(12, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addGap(4, 4, 4)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jcbTamano, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jcbBeber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(51, Short.MAX_VALUE))
        );

        panelCS.setBorder(javax.swing.BorderFactory.createTitledBorder("Agregados"));

        jcbMayo.setText("Mayo");

        jcbKetchup.setText("Ketchup");

        jcbMostaza.setText("Mostaza");

        jcbAmericana.setText("Americana");

        jcbTomate.setText("Tomate");

        jcbPalta.setText("Palta");

        jcbChucrut.setText("Chucrut");

        javax.swing.GroupLayout panelCSLayout = new javax.swing.GroupLayout(panelCS);
        panelCS.setLayout(panelCSLayout);
        panelCSLayout.setHorizontalGroup(
            panelCSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCSLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelCSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jcbMayo)
                    .addComponent(jcbKetchup)
                    .addComponent(jcbMostaza)
                    .addComponent(jcbAmericana)
                    .addComponent(jcbTomate)
                    .addComponent(jcbPalta)
                    .addComponent(jcbChucrut))
                .addContainerGap(37, Short.MAX_VALUE))
        );
        panelCSLayout.setVerticalGroup(
            panelCSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCSLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jcbMayo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jcbKetchup)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jcbMostaza)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jcbAmericana)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jcbTomate)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jcbPalta)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 1, Short.MAX_VALUE)
                .addComponent(jcbChucrut))
        );

        panelP.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createTitledBorder("Agregados"), "Agregados Pizza"));

        jcbExtraQueso.setText("Extra Queso");

        jcbCarne.setText("Carne");

        jcbChoricillos.setText("Choricillos");

        jcbChoclo.setText("Choclo");

        jcbPalmitos.setText("Palmitos");

        jcbEsparrago.setText("Esparrago");
        jcbEsparrago.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbEsparragoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelPLayout = new javax.swing.GroupLayout(panelP);
        panelP.setLayout(panelPLayout);
        panelPLayout.setHorizontalGroup(
            panelPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelPLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jcbChoricillos)
                    .addComponent(jcbChoclo)
                    .addComponent(jcbPalmitos)
                    .addComponent(jcbEsparrago)
                    .addComponent(jcbCarne)
                    .addComponent(jcbExtraQueso))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelPLayout.setVerticalGroup(
            panelPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelPLayout.createSequentialGroup()
                .addComponent(jcbExtraQueso)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jcbCarne)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jcbChoricillos)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jcbChoclo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jcbPalmitos)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jcbEsparrago)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder("Acciones"));

        jbtCalcular.setText("Calcular");
        jbtCalcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtCalcularActionPerformed(evt);
            }
        });

        jbtGuardar.setText("Guardar");
        jbtGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtGuardarActionPerformed(evt);
            }
        });

        jbtSalir.setText("Salir");
        jbtSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtSalirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jbtCalcular)
                    .addComponent(jbtGuardar))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jbtSalir)
                .addContainerGap(35, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jbtCalcular)
                .addGap(18, 18, 18)
                .addComponent(jbtGuardar)
                .addGap(18, 18, 18)
                .addComponent(jbtSalir)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(14, 14, 14))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(panelCS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(panelP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(panelP, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(panelCS, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>                        

    private void jcbEsparragoActionPerformed(java.awt.event.ActionEvent evt) {                                             
        // TODO add your handling code here:
    }                                            

    private void rbtCompletoActionPerformed(java.awt.event.ActionEvent evt) {                                            
habilitaPaneles(true);        // TODO add your handling code here:
    }                                           

    private void rbtSandwichActionPerformed(java.awt.event.ActionEvent evt) {                                            
habilitaPaneles(true);        // TODO add your handling code here:
    }                                           

    private void rbtPizzaActionPerformed(java.awt.event.ActionEvent evt) {                                         
habilitaPaneles(false);        // TODO add your handling code here:
    }                                        

    private void jbtCalcularActionPerformed(java.awt.event.ActionEvent evt) {                                            
        
    }                                           

    private void jbtSalirActionPerformed(java.awt.event.ActionEvent evt) {                                         
System.exit(0);        // TODO add your handling code here:
    }                                        

    private void jbtGuardarActionPerformed(java.awt.event.ActionEvent evt) {                                           
       
                completo = rbtCompleto.getText();
                sandwich=rbtSandwich.getText();
                pizza=rbtPizza.getText();
                tamaño=jcbTamano.getSelectedItem().toString();
                beber=jcbBeber.getSelectedItem().toString();
                mayo=jcbMayo.getText();
                ketchup=jcbKetchup.getText();
                mostaza=jcbMostaza.getText();
                americana=jcbAmericana.getText();
                tomate=jcbTomate.getText();
                palta=jcbPalta.getText();
                chucrut=jcbChucrut.getText();
                EQueso=jcbExtraQueso.getText();
                carne=jcbCarne.getText();
                choricillos=jcbChoricillos.getText();
                choclos=jcbChoclo.getText();
                palmitos=jcbPalmitos.getText();
                esparragos=jcbEsparrago.getText();
                try {
                    String sql = "INSERT INTO pedido ("
                        //+"tipo_pedido,"
                        //+"tipo_pedido,"
                        +"tipo_pedido,"
                        +"tamaño,"
                        +"beber,"
                        +"agregado,"
                        //+"especialidad,"
                        //+"observaciones)"
                        //+"VALUES('"
                        +completo+"','"
                        +sandwich+"','"
                        +pizza+"','"
                        +tamaño+"','"
                        +beber+"')";
                        acc.ejecutarIAE(sql);
                   
                    JOptionPane.showConfirmDialog(null,"Seguro de Grabar?","Confirmación",
                JOptionPane.YES_NO_OPTION,JOptionPane.QUESTION_MESSAGE);
                    JOptionPane.showMessageDialog(null,"Hora ingresada exitosamente");
                    this.setVisible(false);
                }catch (Exception ex)
                {
                    Logger.getLogger(Principal.class.getName()).log(Level.SEVERE,null,ex);
                }
    }                                          
                 
    
    
    public void habilitaPaneles(boolean estado)
    {
        int x=panelCS.getComponentCount();
        int i;
        for (i=0;i<x;i++)
        {
            panelCS.getComponent(i).setEnabled(estado);
        }
        x=panelP.getComponentCount();
        for (i=0;i<x;i++)
        {
            panelP.getComponent(i).setEnabled(!estado);
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify                     
    private javax.swing.ButtonGroup btgTipoPedido;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JButton jbtCalcular;
    private javax.swing.JButton jbtGuardar;
    private javax.swing.JButton jbtSalir;
    private javax.swing.JCheckBox jcbAmericana;
    private javax.swing.JComboBox jcbBeber;
    private javax.swing.JCheckBox jcbCarne;
    private javax.swing.JCheckBox jcbChoclo;
    private javax.swing.JCheckBox jcbChoricillos;
    private javax.swing.JCheckBox jcbChucrut;
    private javax.swing.JCheckBox jcbEsparrago;
    private javax.swing.JCheckBox jcbExtraQueso;
    private javax.swing.JCheckBox jcbKetchup;
    private javax.swing.JCheckBox jcbMayo;
    private javax.swing.JCheckBox jcbMostaza;
    private javax.swing.JCheckBox jcbPalmitos;
    private javax.swing.JCheckBox jcbPalta;
    private javax.swing.JComboBox jcbTamano;
    private javax.swing.JCheckBox jcbTomate;
    private javax.swing.JPanel panelCS;
    private javax.swing.JPanel panelP;
    private javax.swing.JRadioButton rbtCompleto;
    private javax.swing.JRadioButton rbtPizza;
    private javax.swing.JRadioButton rbtSandwich;
    // End of variables declaration                   
}
